base_dir: /home/christophschirninger/ITI/FSI_to_SDO
data:
  B_path: /mnt/disks/data/SDO_171_304
  converted_B_path: /mnt/disks/data/converted/sdo
  A_path: /mnt/disks/data/EUI/FSI
  converted_A_path: /mnt/disks/data/converted/fsi
  num_workers: 4
  iterations_per_epoch: 1000
model:
  input_dim_a: 2
  input_dim_b: 2
  upsampling: 1
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: in_rs_aff
  use_batch_statistic: False
logging:
  wandb_entity: christoph-schirninger
  wandb_project: ITI
  wandb_name: FSI_to_SDO
  wandb_id: null
training:
  epochs: 1000