base_dir: /Users/anna.jungbluth/Desktop/ITI
data:
  B_path: /Users/anna.jungbluth/Desktop/git/rs_tools/data/msg/analysis
  # converted_B_path: 
  A_path: /Users/anna.jungbluth/Desktop/git/rs_tools/data/goes16/analysis
  # converted_A_path:
  num_workers: 1
  iterations_per_epoch: 1000
model:
  input_dim_a: 11
  input_dim_b: 16
  upsampling: 1
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: in_rs_aff
  use_batch_statistic: False
logging:
  wandb_entity: annajungbluth
  wandb_project: ITI
  wandb_name: MSG-to-GOES
  wandb_id: null
training:
  epochs: 1