base_dir: /home/freischem/outputs/miniset/
data:
  A_path: /mnt/disks/data/miniset/msg/geoprocessed
  # converted_A_path:
  B_path: /mnt/disks/data/miniset/goes16/geoprocessed
  # converted_B_path: 
  num_workers: 1
  iterations_per_epoch: 1000
model:
  input_dim_a: 11
  input_dim_b: 16
  upsampling: 0
  discriminator_mode: CHANNELS
  lambda_diversity: 0
  norm: 'none'
  use_batch_statistic: False
logging:
  # wandb_entity: annajungbluth
  # wandb_project: ITI
  # wandb_name: MSG-to-GOES
  # wandb_id: null
  wandb_entity: lilli-freischem
  wandb_project: msg-goes-miniset
  wandb_name: MSG-to-GOES
  wandb_id: null
training:
  epochs: 10